In [179]:
import numpy
from PIL import Image
import sklearn

In [180]:
im = Image.open("sample/download.jpg")
#im.show()
print(im.format, im.size, im.mode)


JPEG (300, 168) RGB


In [181]:
im = im.convert("L")
im = im.resize((150,150))
#im.show()
print(im.format, im.size, im.mode)

None (150, 150) L


In [182]:
arr = numpy.asarray(im)
print(arr)

[[ 39  41  43 ... 101 100 100]
 [ 38  40  43 ... 102 101 101]
 [ 36  39  40 ... 104 102 102]
 ...
 [ 25  25  25 ...  34  34  34]
 [ 25  25  25 ...  33  33  33]
 [ 26  26  26 ...  33  33  33]]


In [183]:
arr = numpy.fft.fft2(arr)
print(arr.shape)

(150, 150)


In [184]:
print(arr[0])

[ 2.47663500e+06+0.00000000e+00j -1.50413424e+05+1.56557963e+05j
 -1.08837550e+05+1.50701568e+05j -1.61084402e+04-8.74070879e+03j
 -1.05090415e+04+6.60287731e+04j -8.20580166e+03+2.19940505e+04j
 -2.69681645e+04+1.57877130e+04j  4.56784710e+03+1.37704171e+04j
 -1.56257375e+04+2.40635544e+04j -5.07216127e+03+1.96210527e+04j
  9.91276628e+02+1.11813470e+04j -6.95661172e+03+1.16523936e+04j
  1.61376425e+03+2.09216757e+03j -1.53153312e+04+7.26811182e+03j
 -3.16582575e+03+1.16218215e+04j -1.46360977e+04+8.07461442e+03j
  6.93109757e+03+1.05201242e+04j -1.09627074e+04+6.68743860e+03j
 -6.37912058e+03+1.03288368e+04j  3.81929854e+03+5.60676712e+03j
 -7.20268576e+03+9.06021343e+03j -5.78566492e+03+5.25456659e+03j
  2.85477652e+03+5.80024074e+03j -7.09864207e+03+6.84871290e+03j
 -3.73506406e+03+4.18915994e+03j -1.16400000e+03+5.79024585e+03j
 -5.61921356e+03+5.48959234e+03j -4.65317914e+03+5.27744193e+03j
 -2.04379439e+03+2.53961995e+03j -4.43484291e+03+6.72023243e+03j
 -3.60950288e+03+4.334023

In [185]:
def high_pass_filter(arr, radius):
    ret = numpy.zeros((arr.shape[0],arr.shape[1]),dtype=complex)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if numpy.abs(arr[i][j])  - radius**2 > 0:
                ret[i][j] = arr[i][j]
            else:
                ret[i][j] = 0
    return ret


In [186]:
arr = high_pass_filter(arr, 100)
print(arr.shape)

6133720913225.0
47134584134.4038
34556564763.41976
335871835.3006348
4470228834.937853
551063437.4327801
976523777.8257016
210479613.65531534
823208323.7030911
410702529.23461
125995149.52242513
184162723.82542083
6971400.200175661
287374819.93761593
145079187.98779377
279404754.8120257
158703126.90069127
164892788.72713402
147368048.51916364
46012878.864781365
133956149.58489402
61074388.57644029
41782541.66169182
97285587.65466753
31489764.57687057
34871842.999999985
61701185.15077348
49493469.46220355
10616765.029090505
64819355.52181951
31802266.58604638
26494264.021782327
19878293.93130793
62751484.573497854
32311494.55407357
20531476.0211884
46400445.91801468
24740379.60385672
23711122.761350702
23828891.831887823
40002916.5575057
2903056.0815632325
28343524.95100466
11532503.666813273
25352850.088185787
16731772.187974317
29364407.271670632
10118788.269019764
14021043.812135875
14481702.082917022
19522666.999999974
13037755.140792064
21885075.18372781
10158867.403938679
19815044

In [187]:
i_arr = numpy.fft.ifft2(arr)

In [188]:
def get_real(i_arr):
    ret = numpy.zeros(i_arr.shape)
    for i in range(i_arr.shape[0]):
        for j in range(i_arr.shape[1]):
            ret[i][j] = numpy.abs(i_arr[i][j])
    return ret

In [189]:
im = Image.fromarray(get_real(i_arr))
im.show()